require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# expectss and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MatchdaysController do


  let(:user) { FactoryGirl.create(:user, role: 1) }
  let(:valid_session) { {user_id: user.id} }

  context "GET" do

    let(:matchday) { FactoryGirl.create(:matchday) }

    context "index" do
      it "assigns all matchdays as @matchdays" do
        matchday
        get :index, {}, valid_session
        assigns(:matchdays).should eq([matchday])
      end
    end

    context "show" do
      it "assigns the requested matchday as @matchday" do
        get :show, {:id => matchday.to_param}, valid_session
        assigns(:matchday).should eq(matchday)
      end
    end

    context "new" do
      it "assigns a new matchday as @matchday" do
        get :new, {}, valid_session
        assigns(:matchday).should be_a_new(Matchday)
      end
    end

    context "edit" do
      it "assigns the requested matchday as @matchday" do
        get :edit, {:id => matchday.to_param}, valid_session
        assigns(:matchday).should eq(matchday)
      end
    end
  end

  context "POST create" do

    let(:valid_attributes) { FactoryGirl.build(:matchday).as_json(:only => [:description]) }

    context "with valid params" do
      it "creates a new Matchday" do
        expect {
          post :create, {:matchday => valid_attributes}, valid_session
        }.to change(Matchday, :count).by(1)
      end

      it "assigns a newly created matchday as @matchday" do
        post :create, {:matchday => valid_attributes}, valid_session
        assigns(:matchday).should be_a(Matchday)
        assigns(:matchday).should be_persisted
      end

      it "redirects to the created match" do
        post :create, {:matchday => valid_attributes}, valid_session
        response.should redirect_to(Matchday.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved matchday as @matchday" do
        # Trigger the behavior that occurs when invalid params are submitted
        Matchday.any_instance.expects(:save).returns(false)
        post :create, {:matchday => {}}, valid_session
        assigns(:matchday).should be_a_new(Matchday)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Matchday.any_instance.expects(:save).returns(false)
        post :create, {:matchday => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  context "PUT update" do

    let(:matchday) { FactoryGirl.create(:matchday) }
    let(:valid_attributes) { FactoryGirl.build(:matchday).as_json(:only => [:description]) }

    context "with valid params" do
      it "updates the requested match" do
        Matchday.any_instance.expects(:update_attributes).with({'these' => 'params'})
        put :update, {:id => matchday.to_param, :matchday => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested matchday as @matchday" do
        put :update, {:id => matchday.to_param, :matchday => valid_attributes}, valid_session
        assigns(:matchday).should eq(matchday)
      end

      it "redirects to the match" do
        put :update, {:id => matchday.to_param, :matchday => valid_attributes}, valid_session
        response.should redirect_to(matchday)
      end
    end

    context "with invalid params" do
      it "assigns the matchday as @matchday" do
        # Trigger the behavior that occurs when invalid params are submitted
        Matchday.any_instance.expects(:save).returns(false)
        put :update, {:id => matchday.to_param, :matchday => {}}, valid_session
        assigns(:matchday).should eq(matchday)
      end

      it "re-renders the 'edit' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Matchday.any_instance.expects(:save).returns(false)
        put :update, {:id => matchday.to_param, :matchday => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  context "DELETE destroy" do
    it "destroys the requested match" do
      matchday = FactoryGirl.create(:matchday)
      expect {
        delete :destroy, {:id => matchday.to_param}, valid_session
      }.to change(Matchday, :count).by(-1)
    end

    it "redirects to the matchdays list" do
      matchday = FactoryGirl.create(:matchday)
      delete :destroy, {:id => matchday.to_param}, valid_session
      response.should redirect_to(matchdays_url)
    end
  end

end
