require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe OpenLigaDbLeaguesController do

  # This should return the minimal set of attributes required to create a valid
  # OpenLigaDbLeague. As you add validations to OpenLigaDbLeague, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # OpenLigaDbLeaguesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all open_liga_db_leagues as @open_liga_db_leagues" do
      open_liga_db_league = OpenLigaDbLeague.create! valid_attributes
      get :index, {}, valid_session
      assigns(:open_liga_db_leagues).should eq([open_liga_db_league])
    end
  end

  describe "GET show" do
    it "assigns the requested open_liga_db_league as @open_liga_db_league" do
      open_liga_db_league = OpenLigaDbLeague.create! valid_attributes
      get :show, {:id => open_liga_db_league.to_param}, valid_session
      assigns(:open_liga_db_league).should eq(open_liga_db_league)
    end
  end

  describe "GET new" do
    it "assigns a new open_liga_db_league as @open_liga_db_league" do
      get :new, {}, valid_session
      assigns(:open_liga_db_league).should be_a_new(OpenLigaDbLeague)
    end
  end

  describe "GET edit" do
    it "assigns the requested open_liga_db_league as @open_liga_db_league" do
      open_liga_db_league = OpenLigaDbLeague.create! valid_attributes
      get :edit, {:id => open_liga_db_league.to_param}, valid_session
      assigns(:open_liga_db_league).should eq(open_liga_db_league)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new OpenLigaDbLeague" do
        expect {
          post :create, {:open_liga_db_league => valid_attributes}, valid_session
        }.to change(OpenLigaDbLeague, :count).by(1)
      end

      it "assigns a newly created open_liga_db_league as @open_liga_db_league" do
        post :create, {:open_liga_db_league => valid_attributes}, valid_session
        assigns(:open_liga_db_league).should be_a(OpenLigaDbLeague)
        assigns(:open_liga_db_league).should be_persisted
      end

      it "redirects to the created open_liga_db_league" do
        post :create, {:open_liga_db_league => valid_attributes}, valid_session
        response.should redirect_to(OpenLigaDbLeague.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved open_liga_db_league as @open_liga_db_league" do
        # Trigger the behavior that occurs when invalid params are submitted
        OpenLigaDbLeague.any_instance.stub(:save).and_return(false)
        post :create, {:open_liga_db_league => {}}, valid_session
        assigns(:open_liga_db_league).should be_a_new(OpenLigaDbLeague)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        OpenLigaDbLeague.any_instance.stub(:save).and_return(false)
        post :create, {:open_liga_db_league => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested open_liga_db_league" do
        open_liga_db_league = OpenLigaDbLeague.create! valid_attributes
        # Assuming there are no other open_liga_db_leagues in the database, this
        # specifies that the OpenLigaDbLeague created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        OpenLigaDbLeague.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => open_liga_db_league.to_param, :open_liga_db_league => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested open_liga_db_league as @open_liga_db_league" do
        open_liga_db_league = OpenLigaDbLeague.create! valid_attributes
        put :update, {:id => open_liga_db_league.to_param, :open_liga_db_league => valid_attributes}, valid_session
        assigns(:open_liga_db_league).should eq(open_liga_db_league)
      end

      it "redirects to the open_liga_db_league" do
        open_liga_db_league = OpenLigaDbLeague.create! valid_attributes
        put :update, {:id => open_liga_db_league.to_param, :open_liga_db_league => valid_attributes}, valid_session
        response.should redirect_to(open_liga_db_league)
      end
    end

    describe "with invalid params" do
      it "assigns the open_liga_db_league as @open_liga_db_league" do
        open_liga_db_league = OpenLigaDbLeague.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        OpenLigaDbLeague.any_instance.stub(:save).and_return(false)
        put :update, {:id => open_liga_db_league.to_param, :open_liga_db_league => {}}, valid_session
        assigns(:open_liga_db_league).should eq(open_liga_db_league)
      end

      it "re-renders the 'edit' template" do
        open_liga_db_league = OpenLigaDbLeague.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        OpenLigaDbLeague.any_instance.stub(:save).and_return(false)
        put :update, {:id => open_liga_db_league.to_param, :open_liga_db_league => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested open_liga_db_league" do
      open_liga_db_league = OpenLigaDbLeague.create! valid_attributes
      expect {
        delete :destroy, {:id => open_liga_db_league.to_param}, valid_session
      }.to change(OpenLigaDbLeague, :count).by(-1)
    end

    it "redirects to the open_liga_db_leagues list" do
      open_liga_db_league = OpenLigaDbLeague.create! valid_attributes
      delete :destroy, {:id => open_liga_db_league.to_param}, valid_session
      response.should redirect_to(open_liga_db_leagues_url)
    end
  end

end
